repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: rook-release
  url: https://charts.rook.io/release
- name: argo
  url: https://argoproj.github.io/argo-helm
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: fluent
  url: https://fluent.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: enix
  url: https://charts.enix.io
- name: metrics-server
  url: https://kubernetes-sigs.github.io/metrics-server
- name: vmware-tanzu
  url: https://vmware-tanzu.github.io/helm-charts
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 4.13.7
  values:
  - values/ingress-nginx.yaml

- name: rook-ceph
  namespace: rook-ceph
  chart: rook-release/rook-ceph
  version: v1.16.9
  values:
  - values/rook-ceph.yaml

- name: rook-ceph-cluster
  namespace: rook-ceph
  chart: rook-release/rook-ceph-cluster
  version: v1.16.9
  values:
  - values/rook-ceph-cluster.yaml
  needs:
  - ingress-nginx/ingress-nginx
  - rook-ceph

- name: argocd
  namespace: argocd
  chart: argo/argo-cd
  version: 9.4.10
  values:
  - values/argocd.yaml

- name: opensearch
  namespace: opensearch
  chart: opensearch/opensearch
  version: 3.2.1
  values:
  - values/opensearch.yaml

- name: fluent-bit-opensearch
  namespace: fluent-bit-opensearch
  chart: fluent/fluent-bit
  version: 0.54.0
  values:
  - values/fluent-bit-opensearch.yaml

- name: fluent-bit-all-service-opensearch
  namespace: fluent-bit-all-service-opensearch
  chart: fluent/fluent-bit
  version: 0.54.0
  values:
  - values/fluent-bit-all-service-opensearch.yaml

- name: kube-prometheus-stack
  namespace: prometheus
  chart: prometheus-community/kube-prometheus-stack
  version: 77.14.0
  values:
  - values/kube-prometheus-stack.yaml

- name: x509-certificate-exporter
  namespace: x509-certificate-exporter
  chart: enix/x509-certificate-exporter
  version: 3.6.0

- name: metrics-server
  namespace: kube-system
  chart: metrics-server/metrics-server
  version: 3.12.0

- name: loki-stack
  namespace: loki-stack
  chart: grafana/loki-stack
  version: 2.10.2
  values:
  - values/loki-stack.yaml

helmDefaults:
  createNamespace: true
